name: panodio
description: An audio interface to the acoustic web
version: 0.1.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_tts: ^3.3.3
  speech_to_text: ^5.4.3
  just_audio: ^0.9.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
